title: "Chetan's Notes and Research"
description: "Computer Science, Security, Math, etc."
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true
  
highlighter: rouge

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/